<a href="https://colab.research.google.com/github/SachiSachu/Nitg/blob/main/multiple_file_in_sequence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import math
import os
edges = int(input('number of edge devices: ')) #this is to take number of devices input

iot = int(input("number of IOT devices: ")) #this line takes number of IoT devices

number of edge devices: 2
number of IOT devices: 10


In [29]:
for klm in range(10):
  m = 0
  while os.path.exists("edgefile%s.npy" % m):
      m += 1
  l = 0
  while os.path.exists("iotfile%s.npy" % l):
      l += 1


  edgeco = []                                 #this array is store the co-ordinates of edge devices
  for i in range(edges):                      #this loop creates the random x,y coordinates 
    ar1 = []
    x = random.randint(0,100)
    ar1.append(x)
    y = random.randint(0,100)
    ar1.append(y)
    edgeco.append(ar1)
  np.savetxt("edgefile%s.npy" % m, edgeco)

  iotco = []                                   #this array holds the the co-ordinates of IoT devices
  for i in range(iot):                         #this loop craetes the random x,y coordinates
    ar1 = []
    x = random.randint(0,100)
    ar1.append(x)
    y = random.randint(0,100)
    ar1.append(y)
    iotco.append(ar1)

  np.savetxt("iotfile%s.npy" % l, iotco)

In [30]:
m = 0
while os.path.exists("edgefile%s.npy" % m):
  el = np.loadtxt("edgefile%s.npy" %m)
  print(el)
  m += 1


[[99. 86.]
 [48. 15.]]
[[45. 72.]
 [54. 75.]]
[[42. 84.]
 [79. 77.]]
[[ 1. 50.]
 [30. 30.]]
[[19. 85.]
 [86. 10.]]
[[74. 44.]
 [12. 56.]]
[[ 7.  2.]
 [69.  7.]]
[[25. 27.]
 [96. 70.]]
[[ 39. 100.]
 [ 87.   8.]]
[[ 5. 68.]
 [67. 79.]]


In [31]:
l = 0
while os.path.exists("iotfile%s.npy" % l):
  loadiot = np.loadtxt("iotfile%s.npy" %l)
  print(loadiot)
  l += 1

[[98. 65.]
 [26. 45.]
 [99. 35.]
 [ 6. 98.]
 [66. 14.]
 [43.  1.]
 [ 9. 66.]
 [61. 23.]
 [66. 86.]
 [ 6. 24.]]
[[50. 25.]
 [73. 94.]
 [39. 36.]
 [88. 42.]
 [91. 78.]
 [52. 77.]
 [10. 86.]
 [11. 38.]
 [96. 58.]
 [71. 17.]]
[[ 92.  15.]
 [ 20.  76.]
 [ 77.  95.]
 [ 22.  70.]
 [ 23.  36.]
 [ 17.  36.]
 [ 76.  80.]
 [100.  99.]
 [ 82.  24.]
 [ 60.   1.]]
[[ 7. 77.]
 [55. 74.]
 [ 9. 95.]
 [91. 48.]
 [86. 47.]
 [76. 76.]
 [65. 34.]
 [ 6. 78.]
 [86. 95.]
 [80. 91.]]
[[ 6. 42.]
 [11. 60.]
 [36. 69.]
 [16. 23.]
 [40. 91.]
 [82. 78.]
 [47. 12.]
 [97. 76.]
 [39. 97.]
 [82. 56.]]
[[66. 17.]
 [54. 90.]
 [73. 47.]
 [65.  0.]
 [92.  7.]
 [58. 87.]
 [95. 72.]
 [62. 31.]
 [88. 66.]
 [67. 67.]]
[[96. 93.]
 [23.  0.]
 [75. 66.]
 [52. 26.]
 [43. 99.]
 [13. 72.]
 [43. 37.]
 [20. 59.]
 [87. 79.]
 [42. 61.]]
[[ 8. 70.]
 [90. 40.]
 [26. 38.]
 [69. 32.]
 [54. 11.]
 [58. 55.]
 [99.  9.]
 [91. 85.]
 [ 9. 84.]
 [29. 11.]]
[[61. 18.]
 [19. 33.]
 [27. 33.]
 [24. 87.]
 [13. 78.]
 [55. 71.]
 [56. 60.]
 [76.  1.]
 [33

In [27]:
"""import os

i = 0
while os.path.exists("sample%s.xml" % i):
    i += 1

fh = open("sample%s.xml" % i, "w")"""

'import os\n\ni = 0\nwhile os.path.exists("sample%s.xml" % i):\n    i += 1\n\nfh = open("sample%s.xml" % i, "w")'

In [28]:
"""i = 0
while os.path.exists("sample%s.npy" % i):
    i += 1

fh = open("sample%s.npy" % i, "w")"""

'i = 0\nwhile os.path.exists("sample%s.npy" % i):\n    i += 1\n\nfh = open("sample%s.npy" % i, "w")'